using System;
using System.Collections.Generic;
using System.Text;

namespace OrangeNBT.Data.Anvil
{
    public class AnvilDataProvider : IGameDataProvider
    {
		private static AnvilDataProvider _instance = new AnvilDataProvider();
		public static AnvilDataProvider Instance => _instance;

		private Dictionary<int, AnvilBlock> _blockMap;

		public string Version => "Anvil 1.13";

		private AnvilDataProvider()
		{
			_blockMap = new Dictionary<int, AnvilBlock>(255);

			Add(new AnvilBlock(0, "air").Opa(0));
			Add(new AnvilBlock(1, "stone"));
			Add(new AnvilBlock(2, "grass"));
			Add(new AnvilBlock(3, "dirt"));
			Add(new AnvilBlock(4, "cobblestone"));
			Add(new AnvilBlock(5, "planks"));
			Add(new AnvilBlock(6, "sapling").Opa(0));
			Add(new AnvilBlock(7, "bedrock"));
			Add(new AnvilBlock(8, "flowing_water").Opa(3));
			Add(new AnvilBlock(9, "water").Opa(0));
			Add(new AnvilBlock(10, "flowing_lava").Lum(15));
			Add(new AnvilBlock(11, "lava").Lum(15));
			Add(new AnvilBlock(12, "sand"));
			Add(new AnvilBlock(13, "gravel"));
			Add(new AnvilBlock(14, "gold_ore"));
			Add(new AnvilBlock(15, "iron_ore"));
			Add(new AnvilBlock(16, "coal_ore"));
			Add(new AnvilBlock(17, "log"));
			Add(new AnvilBlock(18, "leaves").Opa(1));
			Add(new AnvilBlock(19, "sponge"));
			Add(new AnvilBlock(20, "glass").Opa(0));
			Add(new AnvilBlock(21, "lapis_ore"));
			Add(new AnvilBlock(22, "lapis_block"));
			Add(new AnvilBlock(23, "dispenser"));
			Add(new AnvilBlock(24, "sandstone"));
			Add(new AnvilBlock(25, "noteblock"));
			Add(new AnvilBlock(26, "bed").Opa(0));
			Add(new AnvilBlock(27, "golden_rail").Opa(0));
			Add(new AnvilBlock(28, "detector_rail").Opa(0));
			Add(new AnvilBlock(29, "sticky_piston").Opa(0));
			Add(new AnvilBlock(30, "web").Opa(1));
			Add(new AnvilBlock(31, "tallgrass"));
			Add(new AnvilBlock(32, "deadbush").Opa(0));
			Add(new AnvilBlock(33, "piston").Opa(0));
			Add(new AnvilBlock(34, "piston_head").Opa(0));
			Add(new AnvilBlock(35, "wool"));
			Add(new AnvilBlock(36, "piston_extension").Opa(0));
			Add(new AnvilBlock(37, "yellow_flower").Opa(0));
			Add(new AnvilBlock(38, "red_flower").Opa(0));
			Add(new AnvilBlock(39, "brown_mushroom").Opa(0).Lum(1));
			Add(new AnvilBlock(40, "red_mushroom").Opa(0));
			Add(new AnvilBlock(41, "gold_block"));
			Add(new AnvilBlock(42, "iron_block"));
			Add(new AnvilBlock(43, "double_stone_slab"));
			Add(new AnvilBlock(44, "stone_slab"));
			Add(new AnvilBlock(45, "brick_block"));
			Add(new AnvilBlock(46, "tnt"));
			Add(new AnvilBlock(47, "bookshelf"));
			Add(new AnvilBlock(48, "mossy_cobblestone"));
			Add(new AnvilBlock(49, "obsidian"));
			Add(new AnvilBlock(50, "torch").Opa(0).Lum(14));
			Add(new AnvilBlock(51, "fire").Opa(0).Lum(15));
			Add(new AnvilBlock(52, "mob_spawner").Opa(0));
			Add(new AnvilBlock(53, "oak_stairs"));
			Add(new AnvilBlock(54, "chest").Opa(0));
			Add(new AnvilBlock(55, "redstone_wire").Opa(0));
			Add(new AnvilBlock(56, "diamond_ore"));
			Add(new AnvilBlock(57, "diamond_block"));
			Add(new AnvilBlock(58, "crafting_table"));
			Add(new AnvilBlock(59, "wheat").Opa(0));
			Add(new AnvilBlock(60, "farmland"));
			Add(new AnvilBlock(61, "furnace"));
			Add(new AnvilBlock(62, "lit_furnace").Lum(13));
			Add(new AnvilBlock(63, "standing_sign").Opa(0));
			Add(new AnvilBlock(64, "wooden_door").Opa(0));
			Add(new AnvilBlock(65, "ladder").Opa(0));
			Add(new AnvilBlock(66, "rail").Opa(0));
			Add(new AnvilBlock(67, "stone_stairs"));
			Add(new AnvilBlock(68, "wall_sign").Opa(0));
			Add(new AnvilBlock(69, "lever").Opa(0));
			Add(new AnvilBlock(70, "stone_pressure_plate").Opa(0));
			Add(new AnvilBlock(71, "iron_door").Opa(0));
			Add(new AnvilBlock(72, "wooden_pressure_plate").Opa(0));
			Add(new AnvilBlock(73, "redstone_ore"));
			Add(new AnvilBlock(74, "lit_redstone_ore").Lum(9));
			Add(new AnvilBlock(75, "unlit_redstone_torch").Opa(0));
			Add(new AnvilBlock(76, "redstone_torch").Lum(7));
			Add(new AnvilBlock(77, "stone_button").Opa(0));
			Add(new AnvilBlock(78, "snow_layer").Opa(0));
			Add(new AnvilBlock(79, "ice").Opa(3));
			Add(new AnvilBlock(80, "snow"));
			Add(new AnvilBlock(81, "cactus").Opa(0));
			Add(new AnvilBlock(82, "clay"));
			Add(new AnvilBlock(83, "reeds").Opa(0));
			Add(new AnvilBlock(84, "jukebox"));
			Add(new AnvilBlock(85, "fence").Opa(0));
			Add(new AnvilBlock(86, "pumpkin"));
			Add(new AnvilBlock(87, "netherrack"));
			Add(new AnvilBlock(88, "soul_sand"));
			Add(new AnvilBlock(89, "glowstone").Lum(15));
			Add(new AnvilBlock(90, "portal").Lum(11));
			Add(new AnvilBlock(91, "lit_pumpkin").Lum(15));
			Add(new AnvilBlock(92, "cake").Opa(0));
			Add(new AnvilBlock(93, "unpowered_repeater").Opa(0));
			Add(new AnvilBlock(94, "powered_repeater").Opa(0));
			Add(new AnvilBlock(95, "stained_glass").Opa(0));
			Add(new AnvilBlock(96, "trapdoor").Opa(0));
			Add(new AnvilBlock(97, "monster_egg"));
			Add(new AnvilBlock(98, "stonebrick"));
			Add(new AnvilBlock(99, "brown_mushroom_block"));
			Add(new AnvilBlock(100, "red_mushroom_block"));
			Add(new AnvilBlock(101, "iron_bars").Opa(0));
			Add(new AnvilBlock(102, "glass_pane").Opa(0));
			Add(new AnvilBlock(103, "melon_block"));
			Add(new AnvilBlock(104, "pumpkin_stem").Opa(0));
			Add(new AnvilBlock(105, "melon_stem").Opa(0));
			Add(new AnvilBlock(106, "vine").Opa(0));
			Add(new AnvilBlock(107, "fence_gate").Opa(0));
			Add(new AnvilBlock(108, "brick_stairs"));
			Add(new AnvilBlock(109, "stone_brick_stairs"));
			Add(new AnvilBlock(110, "mycelium"));
			Add(new AnvilBlock(111, "waterlily"));
			Add(new AnvilBlock(112, "nether_brick"));
			Add(new AnvilBlock(113, "nether_brick_fence").Opa(0));
			Add(new AnvilBlock(114, "nether_brick_stairs"));
			Add(new AnvilBlock(115, "nether_wart").Opa(0));
			Add(new AnvilBlock(116, "enchanting_table"));
			Add(new AnvilBlock(117, "brewing_stand").Lum(1));
			Add(new AnvilBlock(118, "cauldron").Opa(0));
			Add(new AnvilBlock(119, "end_portal").Lum(15));
			Add(new AnvilBlock(120, "end_portal_frame").Lum(1));
			Add(new AnvilBlock(121, "end_stone"));
			Add(new AnvilBlock(122, "dragon_egg"));
			Add(new AnvilBlock(123, "redstone_lamp"));
			Add(new AnvilBlock(124, "lit_redstone_lamp").Lum(15));
			Add(new AnvilBlock(125, "double_wooden_slab"));
			Add(new AnvilBlock(126, "wooden_slab"));
			Add(new AnvilBlock(127, "cocoa").Opa(0));
			Add(new AnvilBlock(128, "sandstone_stairs"));
			Add(new AnvilBlock(129, "emerald_ore"));
			Add(new AnvilBlock(130, "ender_chest").Lum(7));
			Add(new AnvilBlock(131, "tripwire_hook").Opa(0));
			Add(new AnvilBlock(132, "tripwire").Opa(0));
			Add(new AnvilBlock(133, "emerald_block"));
			Add(new AnvilBlock(134, "spruce_stairs"));
			Add(new AnvilBlock(135, "birch_stairs"));
			Add(new AnvilBlock(136, "jungle_stairs"));
			Add(new AnvilBlock(137, "command_block"));
			Add(new AnvilBlock(138, "beacon").Lum(15));
			Add(new AnvilBlock(139, "cobblestone_wall").Opa(0));
			Add(new AnvilBlock(140, "flower_pot").Opa(0));
			Add(new AnvilBlock(141, "carrots").Opa(0));
			Add(new AnvilBlock(142, "potatoes").Opa(0));
			Add(new AnvilBlock(143, "wooden_button").Opa(0));
			Add(new AnvilBlock(144, "skull"));
			Add(new AnvilBlock(145, "anvil").Opa(0));
			Add(new AnvilBlock(146, "trapped_chest"));
			Add(new AnvilBlock(147, "light_weighted_pressure_plate").Opa(0));
			Add(new AnvilBlock(148, "heavy_weighted_pressure_plate").Opa(0));
			Add(new AnvilBlock(149, "unpowered_comparator"));
			Add(new AnvilBlock(150, "powered_comparator").Lum(9));
			Add(new AnvilBlock(151, "daylight_detector"));
			Add(new AnvilBlock(152, "redstone_block"));
			Add(new AnvilBlock(153, "quartz_ore"));
			Add(new AnvilBlock(154, "hopper"));
			Add(new AnvilBlock(155, "quartz_block"));
			Add(new AnvilBlock(156, "quartz_stairs"));
			Add(new AnvilBlock(157, "activator_rail").Opa(0));
			Add(new AnvilBlock(158, "dropper"));
			Add(new AnvilBlock(159, "stained_hardened_clay"));
			Add(new AnvilBlock(160, "stained_glass_pane").Opa(0));
			Add(new AnvilBlock(161, "leaves2"));
			Add(new AnvilBlock(162, "log2"));
			Add(new AnvilBlock(163, "acacia_stairs"));
			Add(new AnvilBlock(164, "dark_oak_stairs"));
			Add(new AnvilBlock(165, "slime"));
			Add(new AnvilBlock(166, "barrier"));
			Add(new AnvilBlock(167, "iron_trapdoor").Opa(0));
			Add(new AnvilBlock(168, "prismarine"));
			Add(new AnvilBlock(169, "sea_lantern").Lum(15));
			Add(new AnvilBlock(170, "hay_block"));
			Add(new AnvilBlock(171, "carpet").Opa(0));
			Add(new AnvilBlock(172, "hardened_clay"));
			Add(new AnvilBlock(173, "coal_block"));
			Add(new AnvilBlock(174, "packed_ice"));
			Add(new AnvilBlock(175, "double_plant").Opa(0));
			Add(new AnvilBlock(176, "standing_banner"));
			Add(new AnvilBlock(177, "wall_banner"));
			Add(new AnvilBlock(178, "daylight_detector_inverted"));
			Add(new AnvilBlock(179, "red_sandstone"));
			Add(new AnvilBlock(180, "red_sandstone_stairs"));
			Add(new AnvilBlock(181, "double_stone_slab2"));
			Add(new AnvilBlock(182, "stone_slab2"));
			Add(new AnvilBlock(183, "spruce_fence_gate").Opa(0));
			Add(new AnvilBlock(184, "birch_fence_gate").Opa(0));
			Add(new AnvilBlock(185, "jungle_fence_gate").Opa(0));
			Add(new AnvilBlock(186, "dark_oak_fence_gate").Opa(0));
			Add(new AnvilBlock(187, "acacia_fence_gate").Opa(0));
			Add(new AnvilBlock(188, "spruce_fence").Opa(0));
			Add(new AnvilBlock(189, "birch_fence").Opa(0));
			Add(new AnvilBlock(190, "jungle_fence").Opa(0));
			Add(new AnvilBlock(191, "dark_oak_fence").Opa(0));
			Add(new AnvilBlock(192, "acacia_fence").Opa(0));
			Add(new AnvilBlock(193, "spruce_door").Opa(0));
			Add(new AnvilBlock(194, "birch_door").Opa(0));
			Add(new AnvilBlock(195, "jungle_door").Opa(0));
			Add(new AnvilBlock(196, "acacia_door").Opa(0));
			Add(new AnvilBlock(197, "dark_oak_door").Opa(0));
			Add(new AnvilBlock(198, "end_rod").Lum(14));
			Add(new AnvilBlock(199, "chorus_plant").Opa(0));
			Add(new AnvilBlock(200, "chorus_flower").Opa(0));
			Add(new AnvilBlock(201, "purpur_block"));
			Add(new AnvilBlock(202, "purpur_pillar"));
			Add(new AnvilBlock(203, "purpur_stairs"));
			Add(new AnvilBlock(204, "purpur_double_slab"));
			Add(new AnvilBlock(205, "purpur_slab"));
			Add(new AnvilBlock(206, "end_bricks"));
			Add(new AnvilBlock(207, "beetroots").Opa(0));
			Add(new AnvilBlock(208, "grass_path"));
			Add(new AnvilBlock(209, "end_gateway").Lum(15));
			Add(new AnvilBlock(210, "repeating_command_block"));
			Add(new AnvilBlock(211, "chain_command_block"));
			Add(new AnvilBlock(212, "frosted_ice"));
			Add(new AnvilBlock(213, "magma").Lum(3));
			Add(new AnvilBlock(214, "nether_wart_block"));
			Add(new AnvilBlock(215, "red_nether_brick"));
			Add(new AnvilBlock(216, "bone_block"));
			Add(new AnvilBlock(217, "structure_void"));
			Add(new AnvilBlock(218, "observer"));
			Add(new AnvilBlock(219, "white_shulker_box"));
			Add(new AnvilBlock(220, "orange_shulker_box"));
			Add(new AnvilBlock(221, "magenta_shulker_box"));
			Add(new AnvilBlock(222, "light_blue_shulker_box"));
			Add(new AnvilBlock(223, "yellow_shulker_box"));
			Add(new AnvilBlock(224, "lime_shulker_box"));
			Add(new AnvilBlock(225, "pink_shulker_box"));
			Add(new AnvilBlock(226, "gray_shulker_box"));
			Add(new AnvilBlock(227, "silver_shulker_box"));
			Add(new AnvilBlock(228, "cyan_shulker_box"));
			Add(new AnvilBlock(229, "purple_shulker_box"));
			Add(new AnvilBlock(230, "blue_shulker_box"));
			Add(new AnvilBlock(231, "brown_shulker_box"));
			Add(new AnvilBlock(232, "green_shulker_box"));
			Add(new AnvilBlock(233, "red_shulker_box"));
			Add(new AnvilBlock(234, "black_shulker_box"));
			Add(new AnvilBlock(235, "white_glazed_terracotta"));
			Add(new AnvilBlock(236, "orange_glazed_terracotta"));
			Add(new AnvilBlock(237, "magenta_glazed_terracotta"));
			Add(new AnvilBlock(238, "light_blue_glazed_terracotta"));
			Add(new AnvilBlock(239, "yellow_glazed_terracotta"));
			Add(new AnvilBlock(240, "lime_glazed_terracotta"));
			Add(new AnvilBlock(241, "pink_glazed_terracotta"));
			Add(new AnvilBlock(242, "gray_glazed_terracotta"));
			Add(new AnvilBlock(243, "silver_glazed_terracotta"));
			Add(new AnvilBlock(244, "cyan_glazed_terracotta"));
			Add(new AnvilBlock(245, "purple_glazed_terracotta"));
			Add(new AnvilBlock(246, "blue_glazed_terracotta"));
			Add(new AnvilBlock(247, "brown_glazed_terracotta"));
			Add(new AnvilBlock(248, "green_glazed_terracotta"));
			Add(new AnvilBlock(249, "red_glazed_terracotta"));
			Add(new AnvilBlock(250, "black_glazed_terracotta"));
			Add(new AnvilBlock(251, "concrete"));
			Add(new AnvilBlock(252, "concrete_powder"));
			Add(new AnvilBlock(255, "structure_block"));
		}

		private void Add(AnvilBlock block)
		{

		}

		public IBlock GetBlock(int id)
		{
			if (_blockMap.ContainsKey(id))
				return _blockMap[id];
			return null;
		}

	}
}
